Destroying comments, back to full action names
Do not use `destroy` as a property name - when you set this property while initializing component,
bad things will happen (some unintentional method overwrite), and when given ember-view needs to be
removed from DOM, this pops up:

```
Uncaught TypeError: renderNode.emberView.destroy is not a function
```